Table AspNetRoleClaims [headercolor: #175e7a] {
	Id integer [ pk, increment, not null ]
	RoleId varchar(256) [ not null ]
	ClaimType text
	ClaimValue text

	indexes {
		(RoleId) [ name: 'IX_AspNetRoleClaims_RoleId' ]
	}
}

Table AspNetRoles [headercolor: #175e7a] {
	Id varchar(256) [ pk, not null ]
	Name varchar(256)
	NormalizedName varchar(256)
	ConcurrencyStamp text
}

Table AspNetUserClaims [headercolor: #175e7a] {
	Id integer [ pk, increment, not null ]
	UserId varchar(256) [ not null ]
	ClaimType text
	ClaimValue text

	indexes {
		(UserId) [ name: 'IX_AspNetUserClaims_UserId' ]
	}
}

Table AspNetUserLogins [headercolor: #175e7a] {
	LoginProvider varchar(256) [ pk, not null ]
	ProviderKey varchar(256) [ pk, not null ]
	ProviderDisplayName varchar(256)
	UserId varchar(256) [ not null ]

	indexes {
		(UserId) [ name: 'IX_AspNetUserLogins_UserId' ]
	}
}

Table AspNetUserRoles [headercolor: #175e7a] {
	UserId varchar(256) [ pk, not null ]
	RoleId varchar(256) [ pk, not null ]

	indexes {
		(RoleId) [ name: 'IX_AspNetUserRoles_RoleId' ]
	}
}

Table AspNetUserTokens [headercolor: #175e7a] {
	UserId varchar(256) [ pk, not null ]
	LoginProvider varchar(256) [ pk, not null ]
	Name varchar(256) [ pk, not null ]
	Value text
}

Table AspNetUsers [headercolor: #175e7a] {
	Id varchar(256) [ pk, not null ]
	FullName varchar(256) [ not null ]
	DateOfBirth date [ not null ]
	Address text [ not null ]
	UserName varchar(256)
	NormalizedUserName varchar(256)
	Email varchar(256)
	NormalizedEmail varchar(256)
	EmailConfirmed boolean [ not null ]
	PasswordHash text
	SecurityStamp text
	ConcurrencyStamp text
	PhoneNumber varchar(50)
	PhoneNumberConfirmed boolean [ not null ]
	TwoFactorEnabled boolean [ not null ]
	LockoutEnd date
	LockoutEnabled boolean [ not null ]
	AccessFailedCount integer [ not null ]
	Nickname varchar(256)
	Introduction text
	ProfilePicUrl text
	CityId integer [ not null ]
	PostalCode varchar(20) [ not null ]
}

Table Cities [headercolor: #175e7a] {
	Id integer [ pk, increment, not null ]
	CityName varchar(256) [ not null ]
	PostalCode varchar(4) [ not null ]
}

Table PreferenceGroups [headercolor: #175e7a] {
	Id integer [ pk, increment, not null ]
	Name varchar(256) [ not null ]
}

Table Preferences [headercolor: #175e7a] {
	Id integer [ pk, increment, not null ]
	Name varchar(256) [ not null ]
	PreferenceGroupId integer [ not null ]

	indexes {
		(PreferenceGroupId) [ name: 'IX_Preferences_PreferenceGroupId' ]
	}
}

Table RefreshTokens [headercolor: #175e7a] {
	Id integer [ pk, increment, not null ]
	Token text [ not null ]
	UserId varchar(256) [ not null ]
	ExpiresAt timestamp [ not null ]
	IsRevoked boolean [ not null ]
	CreatedAt timestamp [ not null ]

	indexes {
		(UserId) [ name: 'IX_RefreshTokens_UserId' ]
	}
}

Table UserPreferences [headercolor: #175e7a] {
	UserId varchar(256) [ pk, not null ]
	PreferenceId integer [ pk, not null ]
	Id integer [ not null ]

	indexes {
		(PreferenceId) [ name: 'IX_UserPreferences_PreferenceId' ]
	}
}

Table __EFMigrationsHistory [headercolor: #175e7a] {
	MigrationId varchar(150) [ pk, not null ]
	ProductVersion varchar(32) [ not null ]
}

Table CourseBases [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	TeacherId varchar(255) [ not null ]
	Name varchar(255) [ not null ]
	Description text [ not null ]
	CourseType smallint [ not null ]
	CourseDomainId integer [ not null ]
	CourseLevelId integer [ not null ]
	Price numeric [ not null ]
	FirstConsultationFree boolean
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
	PriceCurrencyId uuid [ not null ]
}

Table CourseDomains [headercolor: #175e7a] {
	Id integer [ pk, increment, not null, unique ]
	DomainName varchar(255) [ not null ]
}

Table CourseTags [headercolor: #175e7a] {
	Id integer [ pk, increment, not null, unique ]
	TagName varchar(255) [ not null ]
}

Table CoursesToTags [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	TagId integer [ not null ]
	CourseId uuid [ not null ]
}

Table CourseLevels [headercolor: #175e7a] {
	Id integer [ pk, increment, not null, unique ]
	LevelName varchar(255) [ not null ]
}

Table Languages [headercolor: #175e7a] {
	Id integer [ pk, increment, not null, unique ]
	Name varchar(255) [ not null ]
}

Table CourseLanguages [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	CourseId uuid [ not null ]
	LanguageId integer [ not null ]
}

Table Units [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	CourseId uuid [ not null ]
	Name varchar(255) [ not null ]
	Description varchar(255) [ not null ]
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table Lessons [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	UnitId uuid [ not null ]
	Name varchar(255) [ not null ]
	Description varchar(255) [ not null ]
	HandInId uuid
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table LessonToContents [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	LessonId uuid [ not null ]
	ContentId uuid [ not null ]
}

Table TutoringWalls [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	StudentId varchar(255) [ not null ]
	CourseId uuid [ not null ]
	CreatedAt timestamp [ not null ]
}

Table TutoringWallItems [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	WallId uuid [ not null ]
	Text text
	HandInId uuid
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table WallItemAttachments [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	WallItemId uuid [ not null ]
	ContentId uuid [ not null ]
}

Table Folders [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	Name varchar(255) [ not null ]
	ParentFolderId uuid
	OwnerId varchar(255) [ not null ]
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table ContentItems [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	DisplayName varchar(255) [ not null ]
	FolderId uuid [ not null ]
	ItemType varchar(255) [ not null ]
	OwnerId varchar(255) [ not null ]
	Description varchar(255)
	FileReferenceId uuid
	TestId uuid
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table PhysicalFiles [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	StoragePath varchar(255) [ not null ]
	FileName varchar(255) [ not null ]
	MimeType varchar(255) [ not null ]
	Size bigint [ not null ]
}

Table Tests [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	MaxTime time
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table TestModules [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	TestId uuid [ not null ]
	ModuleType varchar(255) [ not null ]
	Text varchar(255) [ not null ]
	Description varchar(255)
	Points integer
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table TestModuleAnswers [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	ModuleId uuid [ not null ]
	Text varchar(255) [ not null ]
	IsCorrect boolean [ not null ]
}

Table Events [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	Organiser varchar(255) [ not null ]
	Type smallint [ not null ]
	StartTime date [ not null ]
	EndTime date
	Name varchar(255) [ not null ]
	Description varchar(255)
	PathCourseId uuid
	TutoringRoomId uuid
	PathEnrollmentId uuid
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table PathEnrollments [headercolor: #175e7a] {
	id uuid [ pk, not null, unique ]
	CourseId uuid [ not null ]
	AttendantId varchar(255) [ not null ]
	CurrentUnitId uuid [ not null ]
	CurrentLessonId uuid [ not null ]
	CreatedAt timestamp [ not null ]
}

Table Submissions [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	Text text
	HandInId uuid [ not null ]
	SubmitterId varchar(255) [ not null ]
	SubmittedAt timestamp [ not null ]
}

Table SubmissionAttachments [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	SubmissionId uuid [ not null ]
	ContentId uuid [ not null ]
}

Table HandIns [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	DueDate date
	Type varchar(255) [ not null ]
	MaxPoints integer
}

Table HandInFeedbacks [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	Text text
	Grade smallint
	Points integer
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
	SubmissionId uuid [ not null ]
}

Table ChatRooms [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	WallId uuid
	EnrollmentId uuid
	CreatedAt timestamp [ not null ]
}

Table CommunityThreads [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	CourseId uuid [ not null ]
	CreatedAt timestamp [ not null ]
}

Table ChatMessages [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	SenderId varchar(255) [ not null ]
	Text varchar(255) [ not null ]
	ChatId uuid [ not null ]
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Table ParentToStudent [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	ParentId varchar(255) [ not null ]
	StudentId varchar(255) [ not null ]
}

Table Currencies [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	Name varchar(255) [ not null ]
}

Table CommunityMessages [headercolor: #175e7a] {
	Id uuid [ pk, not null, unique ]
	SenderId varchar(255) [ not null ]
	Text varchar(255) [ not null ]
	ThreadId uuid [ not null ]
	CreatedAt timestamp [ not null ]
	UpdatedAt timestamp
}

Ref fk_AspNetRoleClaims_RoleId_AspNetRoles {
	AspNetRoleClaims.RoleId > AspNetRoles.Id [ delete: cascade, update: no action ]
}

Ref fk_AspNetUserClaims_UserId_AspNetUsers {
	AspNetUserClaims.UserId > AspNetUsers.Id [ delete: cascade, update: no action ]
}

Ref fk_AspNetUserLogins_UserId_AspNetUsers {
	AspNetUserLogins.UserId > AspNetUsers.Id [ delete: cascade, update: no action ]
}

Ref fk_AspNetUserRoles_RoleId_AspNetRoles {
	AspNetUserRoles.RoleId > AspNetRoles.Id [ delete: cascade, update: no action ]
}

Ref fk_AspNetUserRoles_UserId_AspNetUsers {
	AspNetUserRoles.UserId > AspNetUsers.Id [ delete: cascade, update: no action ]
}

Ref fk_AspNetUserTokens_UserId_AspNetUsers {
	AspNetUserTokens.UserId > AspNetUsers.Id [ delete: cascade, update: no action ]
}

Ref fk_Preferences_PreferenceGroupId_PreferenceGroups {
	Preferences.PreferenceGroupId > PreferenceGroups.Id [ delete: cascade, update: no action ]
}

Ref fk_RefreshTokens_UserId_AspNetUsers {
	RefreshTokens.UserId > AspNetUsers.Id [ delete: cascade, update: no action ]
}

Ref fk_UserPreferences_UserId_AspNetUsers {
	UserPreferences.UserId > AspNetUsers.Id [ delete: cascade, update: no action ]
}

Ref fk_UserPreferences_PreferenceId_Preferences {
	UserPreferences.PreferenceId > Preferences.Id [ delete: cascade, update: no action ]
}

Ref fk_CourseBases_TeacherId_AspNetUsers {
	CourseBases.TeacherId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_CourseBases_CourseDomainId_CourseDomains {
	CourseBases.CourseDomainId > CourseDomains.Id [ delete: no action, update: no action ]
}

Ref fk_CoursesToTags_TagId_CourseTags {
	CoursesToTags.TagId > CourseTags.Id [ delete: no action, update: no action ]
}

Ref fk_CoursesToTags_CourseId_CourseBases {
	CoursesToTags.CourseId > CourseBases.Id [ delete: no action, update: no action ]
}

Ref fk_CourseBases_CourseLevelId_CourseLevels {
	CourseBases.CourseLevelId > CourseLevels.Id [ delete: no action, update: no action ]
}

Ref fk_CourseLanguages_CourseId_CourseBases {
	CourseLanguages.CourseId > CourseBases.Id [ delete: no action, update: no action ]
}

Ref fk_CourseLanguages_LanguageId_Languages {
	CourseLanguages.LanguageId > Languages.Id [ delete: no action, update: no action ]
}

Ref fk_Units_CourseId_CourseBases {
	Units.CourseId > CourseBases.Id [ delete: no action, update: no action ]
}

Ref fk_Lessons_UnitId_Units {
	Lessons.UnitId > Units.Id [ delete: no action, update: no action ]
}

Ref fk_LessonToContent_LessonId_Lessons {
	LessonToContents.LessonId > Lessons.Id [ delete: no action, update: no action ]
}

Ref fk_TutoringWall_CourseId_CourseBases {
	TutoringWalls.CourseId > CourseBases.Id [ delete: no action, update: no action ]
}

Ref fk_TutoringWall_StudentId_AspNetUsers {
	TutoringWalls.StudentId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_TutoringWallItem_WallId_TutoringWalls {
	TutoringWallItems.WallId > TutoringWalls.Id [ delete: no action, update: no action ]
}

Ref fk_WallItemAttachments_WallItemId_TutoringWallItem {
	WallItemAttachments.WallItemId > TutoringWallItems.Id [ delete: no action, update: no action ]
}

Ref fk_Folders_ParentFolderId_Folders {
	Folders.ParentFolderId > Folders.Id [ delete: no action, update: no action ]
}

Ref fk_Folders_Owner_AspNetUsers {
	Folders.OwnerId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_ContentItems_FolderId_Folders {
	ContentItems.FolderId > Folders.Id [ delete: no action, update: no action ]
}

Ref fk_ContentItems_ReferenceId_PhysicalFiles {
	ContentItems.FileReferenceId > PhysicalFiles.Id [ delete: no action, update: no action ]
}

Ref fk_WallItemAttachments_ContentId_ContentItems {
	WallItemAttachments.ContentId > ContentItems.Id [ delete: no action, update: no action ]
}

Ref fk_LessonToContent_ContentId_ContentItems {
	LessonToContents.ContentId > ContentItems.Id [ delete: no action, update: no action ]
}

Ref fk_ContentItems_OwnerId_AspNetUsers {
	ContentItems.OwnerId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_TestModules_TestId_Tests {
	TestModules.TestId > Tests.Id [ delete: no action, update: no action ]
}

Ref fk_TestModuleAnswers_ModuleId_TestModules {
	TestModuleAnswers.ModuleId > TestModules.Id [ delete: no action, update: no action ]
}

Ref fk_Events_Organiser_AspNetUsers {
	Events.Organiser > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_Enrollments_PathId_CourseBases {
	PathEnrollments.CourseId > CourseBases.Id [ delete: no action, update: no action ]
}

Ref fk_Enrollments_AttendantId_AspNetUsers {
	PathEnrollments.AttendantId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_Enrollments_CurrentUnitId_Units {
	PathEnrollments.CurrentUnitId > Units.Id [ delete: no action, update: no action ]
}

Ref fk_Enrollments_CurrentLessonId_Lessons {
	PathEnrollments.CurrentLessonId > Lessons.Id [ delete: no action, update: no action ]
}

Ref fk_SubmissionAttachments_SubmissionId_Submissions {
	SubmissionAttachments.SubmissionId > Submissions.Id [ delete: no action, update: no action ]
}

Ref fk_SubmissionAttachments_ContentId_ContentItems {
	SubmissionAttachments.ContentId > ContentItems.Id [ delete: no action, update: no action ]
}

Ref fk_Submissions_HandInId_HandIns {
	Submissions.HandInId > HandIns.Id [ delete: no action, update: no action ]
}

Ref fk_ChatRooms_Place_TutoringWalls {
	ChatRooms.WallId - TutoringWalls.Id [ delete: no action, update: no action ]
}

Ref fk_CommunityThreads_CourseId_CourseBases {
	CommunityThreads.CourseId > CourseBases.Id [ delete: no action, update: no action ]
}

Ref fk_Messages_ChatId_ChatRooms {
	ChatMessages.ChatId > ChatRooms.Id [ delete: no action, update: no action ]
}

Ref fk_Submissions_SubmitterId_AspNetUsers {
	Submissions.SubmitterId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_ContentItems_TestId_Tests {
	ContentItems.TestId > Tests.Id [ delete: no action, update: no action ]
}

Ref fk_TutoringWallItem_HandInId_HandIns {
	TutoringWallItems.HandInId > HandIns.Id [ delete: no action, update: no action ]
}

Ref fk_Lessons_HandInId_HandIns {
	Lessons.HandInId > HandIns.Id [ delete: no action, update: no action ]
}

Ref fk_ParentToStudent_ParentId_AspNetUsers {
	ParentToStudent.ParentId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_ParentToStudent_StudentId_AspNetUsers {
	ParentToStudent.StudentId > AspNetUsers.Id [ delete: no action, update: no action ]
}

Ref fk_CourseBases_PriceCurrency_Currencies {
	CourseBases.PriceCurrencyId > Currencies.Id [ delete: no action, update: no action ]
}

Ref fk_HandInFeedbacks_SubmissionId_Submissions {
	HandInFeedbacks.SubmissionId > Submissions.Id [ delete: no action, update: no action ]
}

Ref fk_ChatRooms_EnrollmentId_PathEnrollments {
	ChatRooms.EnrollmentId - PathEnrollments.id [ delete: no action, update: no action ]
}

Ref fk_AspNetUsers_City_Cities {
	AspNetUsers.CityId > Cities.Id [ delete: no action, update: no action ]
}

Ref fk_CommunityMessages_ChatId_CommunityThreads {
	CommunityMessages.ThreadId > CommunityThreads.Id [ delete: no action, update: no action ]
}

Ref fk_Events_PathEnrollmentId_PathEnrollments {
	Events.PathEnrollmentId > PathEnrollments.id [ delete: no action, update: no action ]
}

Ref fk_Events_TutoringRoomId_TutoringWalls {
	Events.TutoringRoomId > TutoringWalls.Id [ delete: no action, update: no action ]
}

Ref fk_Events_PathCourseId_CourseBases {
	Events.PathCourseId > CourseBases.Id [ delete: no action, update: no action ]
}