import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Main page",
  description: "Generated by main page",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body>
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
